set -g default-terminal "xterm-256color"

set -as terminal-overrides ",xterm-ghostty:RGB"
set -ga terminal-overrides ',*256col*:Tc'

setw -g mode-keys vi
set -g renumber-windows on
set -g pane-border-lines double
set -s escape-time 0
set -g status-position top
set -g window-status-current-format "#[bold]#I:#W"
set -g set-clipboard on

set -g status-style bg=default,fg=white
set -g status-position top
set -g status-style bg=#3C3836,fg=white  

set -g status-left-length 100
set -g status-left " #[bold]#S #[nobold] "

set -g status-justify right

set -g window-status-format "#I:#W"
set -g window-status-current-format "#[bold]#I:#[bold,underscore]#W"
set -g window-status-separator "  " 

set -g status-right " "

bind -r C-Left  resize-pane -L 10
bind -r C-Down  resize-pane -D 10
bind -r C-Up    resize-pane -U 10
bind -r C-Right resize-pane -R 10
bind r source-file ~/.config/tmux/tmux.conf\; display "Config reloaded!"

bind-key -n C-S-Up swap-window -t -1\; select-window -t -1
bind-key -n C-S-Down swap-window -t +1\; select-window -t +1

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "pbcopy"


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'christoomey/vim-tmux-navigator'


# TPM init
run '~/.tmux/plugins/tpm/tpm'

unbind-key -n C-\\
unbind-key C-\\

