set -g default-terminal "xterm-256color"

set -as terminal-overrides ",xterm-ghostty:RGB"
set -ga terminal-overrides ',*256col*:Tc'
set -g base-index 1
set -g detach-on-destroy off

setw -g mode-keys vi
set -g renumber-windows on
set -g pane-border-lines double
set -s escape-time 0
# set -g window-status-current-format "#[bold]#I:#W"
set -g set-clipboard on

# ---

# set -g status-style bg=default,fg=white
# set -g status-position top
# set -g status-style bg=#3C3836,fg=white  # gruvbox
# # set -g status-style bg=#1D1F2F,fg=white   # tokyonight
# set -g status-left-length 100
# set -g status-left " #[bold]#S #[nobold] "
# set -g status-justify right
# set -g status-right " "
# set -g window-status-format "#I:#W"
# set -g window-status-current-format "#[bold]#I:#[bold,underscore]#W"
# set -g window-status-separator "  " 


# Status bar

set -g status-position top
set -g status-interval 5
set -g status-left-length 30
set -g status-right-length 50
set -g window-status-separator ""
set -gw automatic-rename on
set -gw automatic-rename-format '#{pane_current_command}'
set -g set-titles on
set -g set-titles-string '#h:#W'

set -g status-justify right

# Theme 
set -g status-style "bg=#282828,fg=#a89984"
set -g status-left "#[fg=#E6D8AF,bg=#4F4845] #S "
set -g status-right "#[fg=#a89984]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}"
set -g window-status-format "#[fg=#a89984] #{?client_prefix,#I:,}#W "
set -g window-status-current-format "#[fg=#ebdbb2,bold] #{?client_prefix,#I:,}#W "
set -g pane-border-style "fg=#504945"
set -g pane-active-border-style "fg=#e5784c"
set -g message-style "bg=#282828,fg=#a89984"
set -g message-command-style "bg=#282828,fg=#a89984"
set -g mode-style "bg=#a89984,fg=#282828"

setw -g clock-mode-colour "#a89984"

# ---


set -g @floax-bind 'b'

bind -r C-Left  resize-pane -L 10
bind -r C-Down  resize-pane -D 10
bind -r C-Up    resize-pane -U 10
bind -r C-Right resize-pane -R 10
bind r source-file ~/.config/tmux/tmux.conf\; display "Config reloaded!"

bind-key -n C-S-Up swap-window -t -1\; select-window -t -1
bind-key -n C-S-Down swap-window -t +1\; select-window -t +1

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "pbcopy"


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'christoomey/vim-tmux-navigator'


# TPM init
run '~/.tmux/plugins/tpm/tpm'

unbind-key -n C-\\
unbind-key C-\\

