#!/bin/bash

options=(
  style=round
  # style=square
  width=3.0
  hidpi=on
  order=above

  active_color=0xffe5784c # gruvbox
  # active_color=0x667fa7fb # tokyonight
  inactive_color=0x00000000
)

borders "${options[@]}"
