require("items.widgets.aerospace")
require("items.widgets.calendar")
require("items.widgets.battery")
require("items.widgets.volume")
require("items.widgets.cpu")
require("items.widgets.keyboard")
require("items.widgets.wifi")
