#!/usr/bin/env bash

# Load Scripting Addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout float

yabai -m config window_opacity on
yabai -m config active_window_opacity 0.98
yabai -m config normal_window_opacity 0.98

opaque_apps=(
  "Zen"
  "Safari"
  "Preview"
  "QuickTime Player"
  "Firefox Nightly"
  # "Code"
)

for app in "${opaque_apps[@]}"; do
  yabai -m rule --add app="^${app}$" opacity=1.0
done

sleep 0.3

for app in "${opaque_apps[@]}"; do
  yabai -m query --windows \
    | jq -r --arg app "$app" '.[] | select(.app == $app) | .id' \
    | while read -r id; do
        yabai -m window "$id" --opacity 1.0
      done
done

# -- working config:
# # Signals for Sketchybar
# yabai -m signal --add event=window_focused action="sketchybar --trigger yabai_refresh"
# yabai -m signal --add event=window_created action="sketchybar --trigger yabai_refresh"
# yabai -m signal --add event=window_destroyed action="sketchybar --trigger yabai_refresh"
# yabai -m signal --add event=window_moved action="sketchybar --trigger yabai_refresh"
# yabai -m signal --add event=application_front_switched action="sketchybar --trigger yabai_refresh"
# yabai -m signal --add event=space_changed action="sketchybar --trigger yabai_refresh"
# yabai -m signal --add event=space_created action="sketchybar --trigger yabai_refresh"
# yabai -m signal --add event=space_destroyed action="sketchybar --trigger yabai_refresh"
#
# # Configs
# yabai -m config window_animation_duration 0.0
#
# yabai -m config layout bsp
# yabai -m config window_placement second_child
#
# yabai -m config top_padding    14
# yabai -m config bottom_padding 12
# yabai -m config left_padding   12
# yabai -m config right_padding  12
# yabai -m config window_gap     12
#
# yabai -m config split_ratio 0.5
# yabai -m config mouse_modifier fn
# yabai -m config mouse_action1 move
# yabai -m config mouse_action2 resize
# yabai -m config focus_follows_mouse off
# yabai -m config window_shadow on
#
# yabai -m config window_opacity on
# yabai -m config active_window_opacity 0.98
# yabai -m config normal_window_opacity 0.98
#
# # --- WINDOW RULES (аналог on-window-detected в AeroSpace) ---
#
# # Floating rules & exceptions
# yabai -m rule --add app="^System Settings$" manage=off grid=8:8:2:1:4:6
# yabai -m rule --add app="^Finder$" manage=off grid=6:5:1:1:3:4
# yabai -m rule --add app="^QuickTime Player$" manage=off opacity=1.0
# yabai -m rule --add sub-role="^AXDialog$" manage=off
# yabai -m rule --add title="^Open$" manage=off
#
# # Initialize named spaces
# $HOME/.config/yabai/setup_spaces.sh
#
# # Route apps to spaces by Label
# yabai -m rule --add app="^Ghostty$" space=main
# yabai -m rule --add app="^Zen$" space=brwse
# yabai -m rule --add app="^Safari$" space=brwse
# yabai -m rule --add app="^Helium$" space=brwse
# yabai -m rule --add app="^Obsidian$" space=note
# yabai -m rule --add app="^Zennotes$" space=note
# yabai -m rule --add app="^Gemini$" space=ai
# yabai -m rule --add app="^ChatGPT$" space=ai
# yabai -m rule --add app="^Spotify$" space=sec
# yabai -m rule --add app="^Telegram$" space=chat
# yabai -m rule --add app="^Messages$" space=chat
# yabai -m rule --add app="^Mail$" space=chat
# yabai -m rule --add app="^Rocket.Chat$" space=chat
# yabai -m rule --add app="^hiddify$" space=sec
# yabai -m rule --add app="^Incy$" space=sec
#
# # Apps that should always be fully opaque
# opaque_apps=(
#   "Zen"
#   "Safari"
#   "Preview"
#   "QuickTime Player"
# )
#
# for app in "${opaque_apps[@]}"; do
#   yabai -m rule --add app="^${app}$" opacity=1.0
# done
#
# sleep 0.3
#
# for app in "${opaque_apps[@]}"; do
#   yabai -m query --windows \
#     | jq -r --arg app "$app" '.[] | select(.app == $app) | .id' \
#     | while read -r id; do
#         yabai -m window "$id" --opacity 1.0
#       done
# done
#
